### ISSUE TITLE
burp 2023.7版本报错

### ISSUE THREAD

**Issue by book4yi** [Tsojan/TsojanScan#23]
能正常加载插件，但是测试pikachu的时候，有明显的sql报错语句未检测出。而且插件那里会报错：java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at burp.ScanFun.SQLIScan.ParamEchoScan(SQLIScan.java:198)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1436)
	at burp.Zm3y.passiveAudit(Unknown Source)
	at burp.Zst5.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by TheCryingGame** [comment]
新版本已优化
